#####
#
# DEFAULTS: https://github.com/anchore/grype
#
#####

#####
#
# OVERRIDES
#
#####

# a list of globs to exclude from scanning, for example:
# exclude:
#   - '/etc/**'
#   - './out/**/*.json'
# same as --exclude ; GRYPE_EXCLUDE env var
#exclude: []
exclude:
  - '/opt/conda/envs/rapids/lib/python3.8/site-packages/dask_sql/jar/DaskSQL.jar'


search:

  indexed-archives: false
    
