#!/bin/bash

echo "##########################################"
echo "##"
echo "## CUSTOM BUILD (hooks/build)"
echo "##"
echo "##########################################"
echo "pwd: `pwd`"
echo "DOCKER_TAG: ${DOCKER_TAG}" # => src/docker
echo "IMAGE_NAME: ${IMAGE_NAME}" # => graphistry/graph-app-kit-st

docker-compose build