#!/bin/bash

echo "##########################################"
echo "##"
echo "## CUSTOM BUILD (hooks/build)"
echo "##"
echo "##########################################"
echo "pwd: `pwd`"
echo "DOCKER_TAG: ${DOCKER_TAG}"
echo "IMAGE_NAME: ${IMAGE_NAME}" # => src/docker

docker-compose build DOCKER_TAG=${DOCKER_TAG}