#!/bin/bash

echo "##########################################"
echo "##"
echo "## CUSTOM BUILD (hooks/build)"
echo "##"
echo "##########################################"
echo "pwd: `pwd`"
echo "DOCKER_TAG: ${DOCKER_TAG}"
echo "IMAGE_NAME: ${IMAGE_NAME}"

docker-compose -f ../src/docker/docker-compose.yml build DOCKER_TAG=${DOCKER_TAG}